[tool.ruff]
# Modo estricto pero práctico
lint.select = ["E", "F", "B", "I"]
# O más básico todavía:
# lint.select = ["E", "F", "I"]

# Opcional: auto-fix
fix = true

# Opcional: formato de imports
line-length = 88
