# Generated by Django 5.0.14 on 2025-08-08 23:39

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [TrigramExtension()]
